name: pkart
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  iconsax_flutter: ^1.0.0
  carousel_slider: ^4.2.1
  readmore: ^3.0.0





  cupertino_icons: ^1.0.6
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^3.0.0





flutter:




  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/onboarding_images/
    - assets/logos/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/users/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic






























