// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGqmmLa4HBvm3EGM7aGrOf9k8ne4Ve4yo',
    appId: '1:772173373632:web:8a9620a6322348dfbb8d25',
    messagingSenderId: '772173373632',
    projectId: 'ecommerceappflutter-3a654',
    authDomain: 'ecommerceappflutter-3a654.firebaseapp.com',
    storageBucket: 'ecommerceappflutter-3a654.appspot.com',
    measurementId: 'G-H77QT9RRNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBESm2OVUwQqST0X6H0Md69IbP0V2T_Ljk',
    appId: '1:772173373632:android:e8fb6cc19763cbcbbb8d25',
    messagingSenderId: '772173373632',
    projectId: 'ecommerceappflutter-3a654',
    storageBucket: 'ecommerceappflutter-3a654.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhtYNunsmq_BcTpe1fo_Arp1vdIEGAfjU',
    appId: '1:772173373632:ios:62c1a20b7f7b02cfbb8d25',
    messagingSenderId: '772173373632',
    projectId: 'ecommerceappflutter-3a654',
    storageBucket: 'ecommerceappflutter-3a654.appspot.com',
    androidClientId: '772173373632-kg61prakslvi70gh8tqvqntpf7ufi4o7.apps.googleusercontent.com',
    iosClientId: '772173373632-d4hvhv1r50iup7r65p6nbk2gos1j8hc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pkart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhtYNunsmq_BcTpe1fo_Arp1vdIEGAfjU',
    appId: '1:772173373632:ios:62c1a20b7f7b02cfbb8d25',
    messagingSenderId: '772173373632',
    projectId: 'ecommerceappflutter-3a654',
    storageBucket: 'ecommerceappflutter-3a654.appspot.com',
    androidClientId: '772173373632-kg61prakslvi70gh8tqvqntpf7ufi4o7.apps.googleusercontent.com',
    iosClientId: '772173373632-d4hvhv1r50iup7r65p6nbk2gos1j8hc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pkart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGqmmLa4HBvm3EGM7aGrOf9k8ne4Ve4yo',
    appId: '1:772173373632:web:c5272b01f39617c8bb8d25',
    messagingSenderId: '772173373632',
    projectId: 'ecommerceappflutter-3a654',
    authDomain: 'ecommerceappflutter-3a654.firebaseapp.com',
    storageBucket: 'ecommerceappflutter-3a654.appspot.com',
    measurementId: 'G-GP1GJ7LK47',
  );
}
